[generator]
implementation = "openplaceholder.impl.generator.openfold3:OpenFold3Generator"
n_diffusion_samples = 5
generate_n_seeds = 5
generator_directory = "/tmp/openfold_3_generator/tyk2"
sequence = "MGSPASDPTVFHKRYLKKIRDLGEGHFGKVSLYCYDPTNDGTGEMVAVKALKADAGPQHRSGWKQEIDILRTLYHEHIIKYKGCCEDAGAASLQLVMEYVPLGSLRDYLPRHSIGLAQLLLFAQQICEGMAYLHAQHYIHRNLAARNVLLDNDRLVKIGDFGLAKAVPEGHEYYRVREDGDSPVFWYAPECLKEYKFYYASDVWSFGVTLYELLTHCDSSQSPPTKFLELIGIAQGQMTVLRLTELLERGERLPRPDKCPAEVYHLMKNCWETEASFRPTFENLIPILKTVHEKYRHHHHHH"

[generator.archiver]
implementation = "openplaceholder.impl.generator.archiver:JSONArchiver"
path = "./example_archive.json"


[generator.ligands]
lig_ejm_31 = 'CC(=O)Nc1cc(NC(=O)c2c(Cl)cccc2Cl)ccn1'
lig_ejm_42 = 'CCC(=O)Nc1cc(NC(=O)c2c(Cl)cccc2Cl)ccn1'
lig_ejm_43 = 'CC(C)C(=O)Nc1cc(NC(=O)c2c(Cl)cccc2Cl)ccn1'
lig_ejm_46 = 'O=C(Nc1ccnc(NC(=O)C2CC2)c1)c1c(Cl)cccc1Cl'
lig_ejm_47 = 'O=C(Nc1ccnc(NC(=O)C2CCC2)c1)c1c(Cl)cccc1Cl'
lig_ejm_48 = 'O=C(Nc1ccnc(NC(=O)C2CCCC2)c1)c1c(Cl)cccc1Cl'
lig_ejm_50 = 'O=C(CO)Nc1cc(NC(=O)c2c(Cl)cccc2Cl)ccn1'
lig_jmc_23 = 'O=C(Nc1ccnc(NC(=O)[C@H]2C[C@H]2F)c1)c1c(Cl)cccc1Cl'
lig_jmc_27 = 'O=C(Nc1ccnc(NC(=O)[C@H]2C[C@H]2Cl)c1)c1c(Cl)cccc1Cl'
lig_jmc_28 = 'C[C@@H]1C[C@@H]1C(=O)Nc1cc(NC(=O)c2c(Cl)cccc2Cl)ccn1'

# per-structure physical/chemical validation. each must pass.
# multiple validators can be stacked.
[[selection.validators]]
implementation = "openplaceholder.impl.validators:PosebustersValidator"

[selection.selector]
implementation = "openplaceholder.impl.selectors:MPOSelector"

# which selectors to use and their weights
[selection.selector.MPOSelector]
metric1 = 1


[assembly.transformation]
implementation = "openplaceholder.impl.transformations:MaxVolumeSiteTransformation"

[assembly.mapping]
implementation = "openplaceholder.impl.mappers:LOMAPMapper"
